const books = [
{id:1,title:"Đắc Nhân Tâm",author:"Dale Carnegie",category:"Kỹ năng sống",rating:4.8,status:"available",year:1936,publisher:"NXB Trẻ",pages:320,description:"Cuốn sách tập trung vào nghệ thuật giao tiếp, ứng xử và xây dựng mối quan hệ tích cực trong cuộc sống.",cover:"cover-one"},
{id:2,title:"Nhà Giả Kim",author:"Paulo Coelho",category:"Văn học",rating:4.9,status:"available",year:1988,publisher:"NXB Hội Nhà Văn",pages:228,description:"Một câu chuyện giàu tính biểu tượng về hành trình theo đuổi ước mơ và tìm kiếm ý nghĩa của cuộc sống.",cover:"cover-two"},
{id:3,title:"Tuổi Trẻ Đáng Giá Bao Nhiêu",author:"Rosie Nguyễn",category:"Kỹ năng sống",rating:4.7,status:"borrowed",year:2016,publisher:"NXB Hội Nhà Văn",pages:285,description:"Những góc nhìn thực tế về học tập, trải nghiệm và phát triển bản thân dành cho người trẻ.",cover:"cover-three"},
{id:4,title:"Think and Grow Rich",author:"Napoleon Hill",category:"Kinh tế",rating:4.8,status:"available",year:1937,publisher:"Tổng hợp",pages:238,description:"Những nguyên tắc về tư duy, mục tiêu và hành động được trình bày qua nhiều câu chuyện và bài học.",cover:"cover-four"},
{id:5,title:"Clean Code",author:"Robert C. Martin",category:"Công nghệ",rating:4.8,status:"available",year:2008,publisher:"Prentice Hall",pages:464,description:"Tài liệu kinh điển về cách viết mã nguồn rõ ràng, dễ đọc, dễ bảo trì và có cấu trúc tốt.",cover:"cover-two"},
{id:6,title:"Atomic Habits",author:"James Clear",category:"Kỹ năng sống",rating:4.9,status:"borrowed",year:2018,publisher:"Avery",pages:320,description:"Phương pháp xây dựng thói quen tốt bằng những thay đổi nhỏ và có hệ thống.",cover:"cover-three"},
{id:7,title:"Sapiens",author:"Yuval Noah Harari",category:"Văn học",rating:4.7,status:"available",year:2011,publisher:"Harper",pages:498,description:"Hành trình nhìn lại lịch sử loài người từ những cộng đồng săn bắt hái lượm đến xã hội hiện đại.",cover:"cover-four"},
{id:8,title:"Marketing 5.0",author:"Philip Kotler",category:"Kinh tế",rating:4.6,status:"available",year:2021,publisher:"Wiley",pages:224,description:"Khám phá cách công nghệ và dữ liệu thay đổi hoạt động marketing trong thời đại mới.",cover:"cover-one"}
];

function header(){
return `<div class="top-bar"><div><i class="fa-solid fa-book-open"></i> Không gian dành cho những người yêu sách</div><div><i class="fa-solid fa-phone"></i> 0123 456 789</div></div>
<header><a class="logo" href="index.html"><div class="logo-icon"><i class="fa-solid fa-book-open"></i></div><div><strong>BOOKIN</strong><span>Library</span></div></a><nav><a href="index.html">Trang chủ</a><a href="books.html">Kho sách</a><a href="books.html">Thể loại</a><a href="index.html#about">Giới thiệu</a><a href="#contact">Liên hệ</a></nav><div class="header-actions"><button class="search-btn" onclick="location.href='books.html'"><i class="fa-solid fa-magnifying-glass"></i></button><button class="login-btn" onclick="alert('Chức năng đăng nhập sẽ được kết nối ở phiên bản tiếp theo.')">Đăng nhập</button><button class="menu-toggle" onclick="alert('Hãy sử dụng menu trên màn hình lớn hoặc mở trang Kho sách.')"><i class="fa-solid fa-bars"></i></button></div></header>`;
}
function footer(){
return `<footer id="contact"><div class="footer-main"><div class="footer-brand"><div class="logo"><div class="logo-icon"><i class="fa-solid fa-book-open"></i></div><div><strong>BOOKIN</strong><span>Library</span></div></div><p>Không gian kết nối bạn với thế giới tri thức.</p></div><div><h3>Khám phá</h3><a href="books.html">Kho sách</a><a href="books.html">Thể loại</a><a href="index.html#books">Sách nổi bật</a></div><div><h3>Bookin</h3><a href="index.html#about">Giới thiệu</a><a href="#contact">Liên hệ</a><a href="#">Hỗ trợ</a></div><div><h3>Theo dõi chúng tôi</h3><div class="social"><a href="#"><i class="fa-brands fa-facebook-f"></i></a><a href="#"><i class="fa-brands fa-instagram"></i></a><a href="#"><i class="fa-brands fa-tiktok"></i></a></div></div></div><div class="footer-bottom"><span>© 2026 Bookin Library</span><span>Made with ♥ for book lovers</span></div></footer>`;
}
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("site-header")?.insertAdjacentHTML("afterbegin",header());document.getElementById("site-footer")?.insertAdjacentHTML("afterbegin",footer());});
function card(b){
const status=b.status==="available"?'<span class="status available">Còn sách</span>':'<span class="status borrowed">Đang mượn</span>';
return `<article class="book-card"><a href="book-detail.html?id=${b.id}"><div class="book-cover ${b.cover}"><span>${String(b.id).padStart(2,"0")}</span><i class="fa-solid fa-book-open"></i></div></a><div class="book-info"><span class="book-category">${b.category.toUpperCase()}</span><h3>${b.title}</h3><p>${b.author}</p><div class="book-bottom"><span><i class="fa-solid fa-star"></i> ${b.rating} &nbsp; ${status}</span><a href="book-detail.html?id=${b.id}" aria-label="Xem chi tiết"><button><i class="fa-solid fa-arrow-right"></i></button></a></div></div></article>`;
}
function renderFeaturedBooks(){const el=document.getElementById("featuredBooks");if(el)el.innerHTML=books.slice(0,4).map(card).join("")}
function initLibraryPage(){
const list=document.getElementById("bookList"), search=document.getElementById("searchInput"), cat=document.getElementById("categoryFilter"), stat=document.getElementById("statusFilter"), count=document.getElementById("resultCount"), empty=document.getElementById("emptyState");
[...new Set(books.map(b=>b.category))].sort().forEach(c=>cat.insertAdjacentHTML("beforeend",`<option value="${c}">${c}</option>`));
const params=new URLSearchParams(location.search); if(params.get("category"))cat.value=params.get("category");
function render(){const q=search.value.toLowerCase().trim(),c=cat.value,s=stat.value;const result=books.filter(b=>(!q||`${b.title} ${b.author} ${b.category}`.toLowerCase().includes(q))&&(!c||b.category===c)&&(!s||b.status===s));list.innerHTML=result.map(card).join("");count.textContent=`Hiển thị ${result.length} / ${books.length} đầu sách`;empty.classList.toggle("hidden",result.length!==0);list.classList.toggle("hidden",result.length===0);}
[search,cat,stat].forEach(x=>x.addEventListener("input",render));document.getElementById("clearFilters").addEventListener("click",()=>{search.value="";cat.value="";stat.value="";render()});render();
}
function initBookDetail(){const el=document.getElementById("bookDetail"),id=Number(new URLSearchParams(location.search).get("id"))||1,b=books.find(x=>x.id===id)||books[0];const status=b.status==="available"?'<span class="status available">Còn sách - Có thể mượn</span>':'<span class="status borrowed">Đang được mượn</span>';el.innerHTML=`<div class="detail-wrap"><div><div class="detail-cover ${b.cover}"><i class="fa-solid fa-book-open"></i></div></div><div class="detail-info"><a class="back-link" href="books.html"><i class="fa-solid fa-arrow-left"></i> Quay lại kho sách</a><span class="book-category" style="display:block;margin-top:25px">${b.category.toUpperCase()}</span><h1>${b.title}</h1><p class="detail-author">Tác giả: <strong>${b.author}</strong></p>${status}<p class="detail-desc" style="margin-top:22px">${b.description}</p><div class="detail-meta"><div class="meta-item"><small>Nhà xuất bản</small><strong>${b.publisher}</strong></div><div class="meta-item"><small>Năm xuất bản</small><strong>${b.year}</strong></div><div class="meta-item"><small>Số trang</small><strong>${b.pages}</strong></div><div class="meta-item"><small>Đánh giá</small><strong>★ ${b.rating}/5</strong></div></div><a href="#" class="primary-btn" onclick="borrowBook(${b.id});return false;">${b.status==="available"?"Mượn sách":"Đăng ký chờ"} <i class="fa-solid fa-book-open"></i></a></div></div>`}
function borrowBook(id){const b=books.find(x=>x.id===id);alert(b.status==="available"?`Đã ghi nhận yêu cầu mượn "${b.title}".`:`Bạn đã được thêm vào danh sách chờ "${b.title}".`);}
