const books = [
{id:1,title:"Đắc Nhân Tâm",author:"Dale Carnegie",category:"Kỹ năng sống",rating:4.8,status:"available",year:1936,publisher:"NXB Trẻ",pages:320,description:"Cuốn sách tập trung vào nghệ thuật giao tiếp, ứng xử và xây dựng mối quan hệ tích cực trong cuộc sống.",cover:"cover-one",image:"https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=700&q=85"},
{id:2,title:"Nhà Giả Kim",author:"Paulo Coelho",category:"Văn học",rating:4.9,status:"available",year:1988,publisher:"NXB Hội Nhà Văn",pages:228,description:"Một câu chuyện giàu tính biểu tượng về hành trình theo đuổi ước mơ và tìm kiếm ý nghĩa của cuộc sống.",cover:"cover-two",image:"https://images.unsplash.com/photo-1511108690759-009cbe5c6e73?auto=format&fit=crop&w=700&q=85"},
{id:3,title:"Tuổi Trẻ Đáng Giá Bao Nhiêu",author:"Rosie Nguyễn",category:"Kỹ năng sống",rating:4.7,status:"borrowed",year:2016,publisher:"NXB Hội Nhà Văn",pages:285,description:"Những góc nhìn thực tế về học tập, trải nghiệm và phát triển bản thân dành cho người trẻ.",cover:"cover-three",image:"https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=700&q=85"},
{id:4,title:"Think and Grow Rich",author:"Napoleon Hill",category:"Kinh tế",rating:4.8,status:"available",year:1937,publisher:"Tổng hợp",pages:238,description:"Những nguyên tắc về tư duy, mục tiêu và hành động được trình bày qua nhiều câu chuyện và bài học.",cover:"cover-four",image:"https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=700&q=85"},
{id:5,title:"Clean Code",author:"Robert C. Martin",category:"Công nghệ",rating:4.8,status:"available",year:2008,publisher:"Prentice Hall",pages:464,description:"Tài liệu kinh điển về cách viết mã nguồn rõ ràng, dễ đọc, dễ bảo trì và có cấu trúc tốt.",cover:"cover-two",image:"https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=700&q=85"},
{id:6,title:"Atomic Habits",author:"James Clear",category:"Kỹ năng sống",rating:4.9,status:"borrowed",year:2018,publisher:"Avery",pages:320,description:"Phương pháp xây dựng thói quen tốt bằng những thay đổi nhỏ và có hệ thống.",cover:"cover-three",image:"https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=700&q=85"},
{id:7,title:"Sapiens",author:"Yuval Noah Harari",category:"Văn học",rating:4.7,status:"available",year:2011,publisher:"Harper",pages:498,description:"Hành trình nhìn lại lịch sử loài người từ những cộng đồng săn bắt hái lượm đến xã hội hiện đại.",cover:"cover-four",image:"https://images.unsplash.com/photo-1526243741027-444d633d7365?auto=format&fit=crop&w=700&q=85"},
{id:8,title:"Marketing 5.0",author:"Philip Kotler",category:"Kinh tế",rating:4.6,status:"available",year:2021,publisher:"Wiley",pages:224,description:"Khám phá cách công nghệ và dữ liệu thay đổi hoạt động marketing trong thời đại mới.",cover:"cover-one",image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=700&q=85"},
{id:9,title:"Muôn Kiếp Nhân Sinh",author:"Nguyên Phong",category:"Tâm lý",rating:4.8,status:"available",year:2020,publisher:"First News",pages:416,description:"Những câu chuyện về nhân quả, lựa chọn và hành trình khám phá chiều sâu của con người.",cover:"cover-two",image:"https://images.unsplash.com/photo-1474932430478-367dbb6832c1?auto=format&fit=crop&w=700&q=85"},
{id:10,title:"Vũ Trụ",author:"Carl Sagan",category:"Khoa học",rating:4.9,status:"available",year:1980,publisher:"Random House",pages:384,description:"Một chuyến du hành đầy cảm hứng qua các vì sao, lịch sử tự nhiên và vị trí của con người trong vũ trụ.",cover:"cover-four",image:"https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=700&q=85"},
{id:11,title:"Lược Sử Thời Gian",author:"Stephen Hawking",category:"Khoa học",rating:4.8,status:"borrowed",year:1988,publisher:"Bantam Books",pages:256,description:"Câu chuyện về không gian, thời gian, hố đen và những câu hỏi lớn nhất của khoa học hiện đại.",cover:"cover-one",image:"https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=700&q=85"},
{id:12,title:"Nghệ Thuật Tối Giản",author:"Fumio Sasaki",category:"Nghệ thuật",rating:4.6,status:"available",year:2015,publisher:"W.W. Norton",pages:288,description:"Gợi ý thực tế để sống nhẹ nhàng hơn, tập trung vào điều quan trọng và tìm lại khoảng thở cho tâm trí.",cover:"cover-three",image:"https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=700&q=85"},
{id:13,title:"Dế Mèn Phiêu Lưu Ký",author:"Tô Hoài",category:"Thiếu nhi",rating:4.9,status:"available",year:1941,publisher:"Kim Đồng",pages:180,description:"Cuộc phiêu lưu kinh điển của chú Dế Mèn qua những miền đất và bài học trưởng thành đáng nhớ.",cover:"cover-four",image:"https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?auto=format&fit=crop&w=700&q=85"},
{id:14,title:"Đi Tìm Lẽ Sống",author:"Viktor E. Frankl",category:"Tâm lý",rating:4.9,status:"available",year:1946,publisher:"Beacon Press",pages:184,description:"Một góc nhìn sâu sắc về nghị lực, hy vọng và khả năng tìm thấy ý nghĩa ngay trong nghịch cảnh.",cover:"cover-two",image:"https://images.unsplash.com/photo-1455885666463-8d8a5f5f5c97?auto=format&fit=crop&w=700&q=85"},
{id:15,title:"Những Người Khốn Khổ",author:"Victor Hugo",category:"Văn học",rating:4.8,status:"borrowed",year:1862,publisher:"Penguin Classics",pages:1248,description:"Thiên sử thi về tình yêu, lòng trắc ẩn và cuộc đấu tranh tìm kiếm công lý trong xã hội.",cover:"cover-one",image:"https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=700&q=85"},
{id:16,title:"Lịch Sử Việt Nam",author:"Nguyễn Khắc Thuần",category:"Lịch sử",rating:4.7,status:"available",year:2018,publisher:"NXB Giáo Dục",pages:352,description:"Tổng quan sinh động về những dấu mốc, nhân vật và câu chuyện làm nên lịch sử Việt Nam.",cover:"cover-three",image:"https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=700&q=85"},
{id:17,title:"Bố Già",author:"Mario Puzo",category:"Văn học",rating:4.8,status:"available",year:1969,publisher:"G.P. Putnam's Sons",pages:448,description:"Một tiểu thuyết giàu kịch tính về gia đình, quyền lực, lòng trung thành và những lựa chọn khó khăn.",cover:"cover-four",image:"https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=700&q=85"},
{id:18,title:"Nghệ Thuật Đi Khắp Thế Gian",author:"Bill Bryson",category:"Du ký",rating:4.6,status:"available",year:1998,publisher:"Broadway Books",pages:544,description:"Những quan sát dí dỏm và bất ngờ về các vùng đất, con người và nền văn hóa trên thế giới.",cover:"cover-two",image:"https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=700&q=85"},
{id:19,title:"Thiết Kế Của Tương Lai",author:"Don Norman",category:"Công nghệ",rating:4.7,status:"available",year:2013,publisher:"Basic Books",pages:368,description:"Cách công nghệ, thiết kế và tư duy lấy con người làm trung tâm định hình thế giới ngày mai.",cover:"cover-one",image:"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=700&q=85"},
{id:20,title:"Tư Duy Nhanh Và Chậm",author:"Daniel Kahneman",category:"Kinh tế",rating:4.8,status:"borrowed",year:2011,publisher:"Farrar, Straus and Giroux",pages:512,description:"Khám phá hai hệ thống tư duy ảnh hưởng đến cách chúng ta phán đoán, lựa chọn và hành động.",cover:"cover-three",image:"https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=700&q=85"}
];

function header(){
return `<div class="top-bar"><div><i class="fa-solid fa-book-open"></i> Không gian dành cho những người yêu sách</div><div class="top-bar-contact"><span><i class="fa-solid fa-clock"></i> Mở cửa mỗi ngày 8:00 - 21:00</span><span><i class="fa-solid fa-phone"></i> 0123 456 789</span></div></div>
<header><a class="logo" href="index.html" aria-label="Bookin - Trang chủ"><div class="logo-icon"><i class="fa-solid fa-book-open"></i></div><div><strong>BOOKIN</strong><span>Library & beyond</span></div></a><nav class="main-nav"><a href="index.html">Trang chủ</a><a href="books.html">Kho sách <i class="fa-solid fa-chevron-down"></i></a><a href="books.html?category=Văn học">Thể loại</a><a href="index.html#about">Câu chuyện</a><a href="#contact">Liên hệ</a></nav><div class="header-actions"><button class="search-btn" aria-label="Tìm kiếm sách" onclick="location.href='books.html'"><i class="fa-solid fa-magnifying-glass"></i><span>Tìm sách</span></button><button class="login-btn" onclick="alert('Chức năng đăng nhập sẽ được kết nối ở phiên bản tiếp theo.')"><i class="fa-regular fa-user"></i><span>Đăng nhập</span></button><button class="menu-toggle" aria-label="Mở menu" aria-expanded="false"><i class="fa-solid fa-bars"></i></button></div><div class="mobile-menu"><a href="index.html">Trang chủ</a><a href="books.html">Kho sách</a><a href="books.html?category=Văn học">Thể loại</a><a href="index.html#about">Câu chuyện</a><a href="#contact">Liên hệ</a></div></header>`;
}
function footer(){
return `<footer id="contact"><div class="footer-main"><div class="footer-brand"><div class="logo"><div class="logo-icon"><i class="fa-solid fa-book-open"></i></div><div><strong>BOOKIN</strong><span>Library</span></div></div><p>Không gian kết nối bạn với thế giới tri thức.</p></div><div><h3>Khám phá</h3><a href="books.html">Kho sách</a><a href="books.html">Thể loại</a><a href="index.html#books">Sách nổi bật</a></div><div><h3>Bookin</h3><a href="index.html#about">Giới thiệu</a><a href="#contact">Liên hệ</a><a href="#">Hỗ trợ</a></div><div><h3>Theo dõi chúng tôi</h3><div class="social"><a href="#"><i class="fa-brands fa-facebook-f"></i></a><a href="#"><i class="fa-brands fa-instagram"></i></a><a href="#"><i class="fa-brands fa-tiktok"></i></a></div></div></div><div class="footer-bottom"><span>© 2026 Bookin Library</span><span>Made with ♥ for book lovers</span></div></footer>`;
}
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("site-header")?.insertAdjacentHTML("afterbegin",header());document.getElementById("site-footer")?.insertAdjacentHTML("afterbegin",footer());const toggle=document.querySelector(".menu-toggle"),menu=document.querySelector(".mobile-menu");toggle?.addEventListener("click",()=>{const open=menu.classList.toggle("is-open");toggle.setAttribute("aria-expanded",open);toggle.innerHTML=open?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>';});document.querySelectorAll(".main-nav a, .mobile-menu a").forEach(link=>{if(link.pathname===location.pathname&&!link.hash)link.classList.add("active");});});
function card(b){
const status=b.status==="available"?'<span class="status available">Còn sách</span>':'<span class="status borrowed">Đang mượn</span>';
return `<article class="book-card"><a href="book-detail.html?id=${b.id}"><div class="book-cover ${b.cover}"><img src="${b.image}" alt="Bìa sách ${b.title}" loading="lazy" onerror="this.style.display='none'"><span>${String(b.id).padStart(2,"0")}</span><i class="fa-solid fa-book-open"></i></div></a><div class="book-info"><span class="book-category">${b.category.toUpperCase()}</span><h3>${b.title}</h3><p>${b.author}</p><div class="book-bottom"><span><i class="fa-solid fa-star"></i> ${b.rating} &nbsp; ${status}</span><a href="book-detail.html?id=${b.id}" aria-label="Xem chi tiết"><button><i class="fa-solid fa-arrow-right"></i></button></a></div></div></article>`;
}
function renderFeaturedBooks(){const el=document.getElementById("featuredBooks");if(el)el.innerHTML=books.slice(0,4).map(card).join("")}
function initLibraryPage(){
const list=document.getElementById("bookList"), search=document.getElementById("searchInput"), cat=document.getElementById("categoryFilter"), stat=document.getElementById("statusFilter"), count=document.getElementById("resultCount"), empty=document.getElementById("emptyState");
[...new Set(books.map(b=>b.category))].sort().forEach(c=>cat.insertAdjacentHTML("beforeend",`<option value="${c}">${c}</option>`));
const params=new URLSearchParams(location.search); if(params.get("category"))cat.value=params.get("category");
function render(){const q=search.value.toLowerCase().trim(),c=cat.value,s=stat.value;const result=books.filter(b=>(!q||`${b.title} ${b.author} ${b.category}`.toLowerCase().includes(q))&&(!c||b.category===c)&&(!s||b.status===s));list.innerHTML=result.map(card).join("");count.textContent=`Hiển thị ${result.length} / ${books.length} đầu sách`;empty.classList.toggle("hidden",result.length!==0);list.classList.toggle("hidden",result.length===0);}
[search,cat,stat].forEach(x=>x.addEventListener("input",render));document.getElementById("clearFilters").addEventListener("click",()=>{search.value="";cat.value="";stat.value="";render()});render();
}
function initBookDetail(){const el=document.getElementById("bookDetail"),id=Number(new URLSearchParams(location.search).get("id"))||1,b=books.find(x=>x.id===id)||books[0];const status=b.status==="available"?'<span class="status available">Còn sách - Có thể mượn</span>':'<span class="status borrowed">Đang được mượn</span>';el.innerHTML=`<div class="detail-wrap"><div><div class="detail-cover ${b.cover}"><i class="fa-solid fa-book-open"></i></div></div><div class="detail-info"><a class="back-link" href="books.html"><i class="fa-solid fa-arrow-left"></i> Quay lại kho sách</a><span class="book-category" style="display:block;margin-top:25px">${b.category.toUpperCase()}</span><h1>${b.title}</h1><p class="detail-author">Tác giả: <strong>${b.author}</strong></p>${status}<p class="detail-desc" style="margin-top:22px">${b.description}</p><div class="detail-meta"><div class="meta-item"><small>Nhà xuất bản</small><strong>${b.publisher}</strong></div><div class="meta-item"><small>Năm xuất bản</small><strong>${b.year}</strong></div><div class="meta-item"><small>Số trang</small><strong>${b.pages}</strong></div><div class="meta-item"><small>Đánh giá</small><strong>★ ${b.rating}/5</strong></div></div><a href="#" class="primary-btn" onclick="borrowBook(${b.id});return false;">${b.status==="available"?"Mượn sách":"Đăng ký chờ"} <i class="fa-solid fa-book-open"></i></a></div></div>`}
function borrowBook(id){const b=books.find(x=>x.id===id);alert(b.status==="available"?`Đã ghi nhận yêu cầu mượn "${b.title}".`:`Bạn đã được thêm vào danh sách chờ "${b.title}".`);}
