const books = [
  {
    id: 1,
    title: "Nhà Giả Kim",
    author: "Paulo Coelho",
    category: "Văn học",
    year: 1988,
    pages: 228,
    status: "available",
    statusText: "Có sẵn",
    emoji: "📕",
    color: "#d9b18d",
    description: "Một câu chuyện truyền cảm hứng về hành trình theo đuổi ước mơ và lắng nghe tiếng gọi của trái tim."
  },
  {
    id: 2,
    title: "Tuổi Trẻ Đáng Giá Bao Nhiêu",
    author: "Rosie Nguyễn",
    category: "Kỹ năng",
    year: 2016,
    pages: 285,
    status: "available",
    statusText: "Có sẵn",
    emoji: "📙",
    color: "#e2b15f",
    description: "Những chia sẻ gần gũi về học tập, trải nghiệm, đọc sách và cách sống trọn vẹn những năm tháng tuổi trẻ."
  },
  {
    id: 3,
    title: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    category: "Kỹ năng",
    year: 1936,
    pages: 320,
    status: "borrowed",
    statusText: "Đang mượn",
    emoji: "📘",
    color: "#9eabb7",
    description: "Cuốn sách kinh điển về nghệ thuật giao tiếp và cách xây dựng những mối quan hệ tích cực."
  },
  {
    id: 4,
    title: "Harry Potter",
    author: "J. K. Rowling",
    category: "Giả tưởng",
    year: 1997,
    pages: 309,
    status: "available",
    statusText: "Có sẵn",
    emoji: "📗",
    color: "#9eaa82",
    description: "Hành trình kỳ diệu của Harry Potter tại trường phù thủy Hogwarts cùng những người bạn."
  },
  {
    id: 5,
    title: "Muôn Kiếp Nhân Sinh",
    author: "Nguyên Phong",
    category: "Tâm lý",
    year: 2020,
    pages: 400,
    status: "available",
    statusText: "Có sẵn",
    emoji: "📔",
    color: "#c9957d",
    description: "Một góc nhìn sâu sắc về nhân sinh, những lựa chọn và các bài học trong cuộc sống."
  },
  {
    id: 6,
    title: "Cây Cam Ngọt Của Tôi",
    author: "José Mauro de Vasconcelos",
    category: "Văn học",
    year: 1968,
    pages: 228,
    status: "borrowed",
    statusText: "Đang mượn",
    emoji: "📒",
    color: "#d8a982",
    description: "Câu chuyện cảm động về tuổi thơ, tình yêu thương và những điều giản dị trong cuộc sống."
  },
  {
    id: 7,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Phát triển bản thân",
    year: 2018,
    pages: 320,
    status: "available",
    statusText: "Có sẵn",
    emoji: "📓",
    color: "#b5a28e",
    description: "Phương pháp xây dựng thói quen tốt từ những thay đổi rất nhỏ nhưng có sức ảnh hưởng lâu dài."
  },
  {
    id: 8,
    title: "Đi Tìm Lẽ Sống",
    author: "Viktor E. Frankl",
    category: "Tâm lý",
    year: 1946,
    pages: 184,
    status: "available",
    statusText: "Có sẵn",
    emoji: "📚",
    color: "#c4a98b",
    description: "Những suy ngẫm sâu sắc về ý nghĩa cuộc sống, nghị lực và hy vọng của con người."
  },
  {
    id: 9,
    title: "Dế Mèn Phiêu Lưu Ký",
    author: "Tô Hoài",
    category: "Thiếu nhi",
    year: 1941,
    pages: 144,
    status: "available",
    statusText: "Có sẵn",
    emoji: "📕",
    color: "#b6aa76",
    description: "Tác phẩm quen thuộc của văn học Việt Nam kể về hành trình trưởng thành của Dế Mèn."
  },
  {
    id: 10,
    title: "Cho Tôi Xin Một Vé Đi Tuổi Thơ",
    author: "Nguyễn Nhật Ánh",
    category: "Văn học",
    year: 2008,
    pages: 208,
    status: "available",
    statusText: "Có sẵn",
    emoji: "📙",
    color: "#d8b08b",
    description: "Một chuyến trở về tuổi thơ trong trẻo, hài hước và đầy những ký ức đáng yêu."
  }
];